print("##################################")
print("#                                #")
print("#     Muhammad Rayhan Akbar      #")
print("#         2610817110012          #")
print("#                                #")
print("##################################")